plugins:
  game_sheet_enabled:
    default: true
    client: false

  game_sheet_allowed_category_id:
    default: 1
    client: false

  game_sheet_deepl_api_key:
    default: ""
    secret: true
    client: false

  game_sheet_bgg_token:
    default: ""
    secret: true
    client: false

  game_sheet_target_locale:
    default: "FR"
    client: false
